---

driver:
  name: ec2
  associate_public_ip: <%= ENV['AWS_PUBLIC_IP'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids:
  <% (1..5).collect { |n| ENV["AWS_SECURITY_GROUP_#{n}"] }.compact.each do |secgroup| %>
    - <%= secgroup %>
  <% end %>
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  vpc_id: <%= ENV['AWS_VPC_ID'] %>
  iam_profile_name: <%= ENV['AWS_IAM_INSTANCE_PROFILE_1'] %>
  region: <%= ENV['AWS_REGION'] %>
  instance_type: t2.nano

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44
  data_bags_path: test/data_bags
  encrypted_data_bag_secret_key_path: test/data_bags/encrypted_data_bag_secret
  roles_path: test/roles
  environments_path: test/environments

platforms:
  - name: amzn-2016-latest-instance-store
    driver:
      image_search:
        name: amzn-ami-hvm-2016.*x86_64-s3
      tags:
        Name: kitchen-trt-proxy-is-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        Owner: <%= ENV['USER'] %>
  - name: amzn-2016-latest-ebs
    driver:
      image_search:
        name: amzn-ami-hvm-2016.*x86_64-gp2
      tags:
        Name: kitchen-trt-proxy-ebs-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        Owner: <%= ENV['USER'] %>

transport:
  username: ec2-user
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

suites:
  - name: dev
    run_list:
      - role[trt_awsapi_proxy]
    provisioner:
      client_rb:
        environment: trt_awsapi_proxy_dev
    includes: [amzn-2016-latest-ebs]
  - name: prd
    run_list:
      - role[trt_awsapi_proxy]
    provisioner:
      client_rb:
        environment: trt_awsapi_proxy_prd
    includes: [amzn-2016-latest-ebs]
